apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: taskapp.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://taskapp-kops-state-276945910356/taskapp.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.28.8
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0411bf648bd0869ec
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  topology:
    masters: private
    nodes: private
    dns:
      type: Private
  subnets:
  - cidr: 10.0.0.0/24
    id: subnet-0e4aa1cf6c06d4bda
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.0.1.0/24
    id: subnet-04bd0330c4db90b95
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.0.2.0/24
    id: subnet-020b6926ac357f625
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 10.0.10.0/24
    id: subnet-04533ff761d2fbf20
    name: us-east-1a-private
    type: Private
    zone: us-east-1a
  - cidr: 10.0.11.0/24
    id: subnet-0dcb400feac962910
    name: us-east-1b-private
    type: Private
    zone: us-east-1b
  - cidr: 10.0.12.0/24
    id: subnet-085fa37cc3fa8e7a1
    name: us-east-1c-private
    type: Private
    zone: us-east-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: master-us-east-1a
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: master-us-east-1b
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: master-us-east-1c
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: nodes-us-east-1a
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1a-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: nodes-us-east-1b
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1b-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
  name: nodes-us-east-1c
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1c-private
