apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: taskapp.ayodave.is-a.dev
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://taskapp-kops-state-276945910356/taskapp.ayodave.is-a.dev
  dnsZone: ayodave.is-a.dev
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
    backups:
      backupStore: s3://taskapp-kops-state-276945910356/taskapp.ayodave.is-a.dev/backups/etcd/main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.28.8
  masterPublicName: api.taskapp.ayodave.is-a.dev
  networkCIDR: 10.0.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
  subnets:
  - cidr: 10.0.0.0/24
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 10.0.1.0/24
    name: us-east-1b
    type: Public
    zone: us-east-1b
  - cidr: 10.0.2.0/24
    name: us-east-1c
    type: Public
    zone: us-east-1c
  - cidr: 10.0.10.0/24
    name: us-east-1a-private
    type: Private
    zone: us-east-1a
  - cidr: 10.0.11.0/24
    name: us-east-1b-private
    type: Private
    zone: us-east-1b
  - cidr: 10.0.12.0/24
    name: us-east-1c-private
    type: Private
    zone: us-east-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: master-us-east-1a
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: master-us-east-1b
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: master-us-east-1c
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: nodes-us-east-1a
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1a-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: nodes-us-east-1b
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1b-private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: taskapp.ayodave.is-a.dev
  name: nodes-us-east-1c
spec:
  image: ami-0c101f26f147fa7fd
  machineType: t3.large
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - us-east-1c-private
