configuration:
  provider: aws
  backupStorageLocation:
    bucket: taskapp-kops-state-276945910356
    prefix: velero-backups
    config:
      region: us-east-1
  volumeSnapshotLocation:
    config:
      region: us-east-1

credentials:
  useSecret: true

initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.8.0
  volumeMounts:
  - mountPath: /target
    name: plugins

schedules:
  daily-backup:
    schedule: "0 2 * * *"
    template:
      ttl: 168h
      includedNamespaces:
      - taskapp
